name: Daily i18n Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  pull-requests: write # for peter-evans/create-pull-request to create PRs
  contents: write # for git push

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      env_valid: ${{ steps.validate_env.outputs.env_valid }}
    steps:
      - name: Validate environment
        id: validate_env
        run: |
          echo "🔍 Validating environment..."

          # Check required secrets
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "❌ OPENAI_API_KEY is missing"
            echo "env_valid=false" >> $GITHUB_OUTPUT
            echo "ERROR_VALIDATE_ENV=OPENAI_API_KEY secret is not configured" >> $GITHUB_ENV
            exit 1
          fi

          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "❌ GH_TOKEN is missing"
            echo "env_valid=false" >> $GITHUB_OUTPUT
            echo "ERROR_VALIDATE_ENV=GH_TOKEN secret is not configured" >> $GITHUB_ENV
            exit 1
          fi

          # Test OpenAI API connectivity (optional, with timeout)
          echo "🌐 Testing OpenAI API connectivity..."
          if timeout 30s curl -s -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
             ${{ secrets.OPENAI_PROXY_URL || 'https://api.openai.com' }}/v1/models >/dev/null 2>&1; then
            echo "✅ OpenAI API accessible"
          else
            echo "⚠️ OpenAI API test failed (but continuing...)"
          fi

  update-i18n:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: validate
    if: needs.validate.outputs.env_valid == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ secrets.BUN_VERSION }}

      - name: Install deps
        run: bun i

      - name: Update i18n
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_PROXY_URL: ${{ secrets.OPENAI_PROXY_URL }}
        run: |
          echo "🌐 Running i18n update..."
          bun run i18n > i18n_update.log 2>&1 || true

      - name: create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            locales/**/*.json
          labels: |
            i18n
            automated
            style
          branch: style/auto-i18n
          delete-branch: true
          title: "🤖 style: update i18n"
          commit-message: "💄 style: update i18n"
          body: |
            This PR was automatically generated by the i18n update workflow.
            Please review the changes and merge if everything looks good.

            ## 🤖 Automation Info
              - Workflow: `${{ github.workflow }}`
              - Run ID: `${{ github.run_id }}`
              - Commit: `${{ github.sha }}`

            <details>
            <summary>i18n Update Log</summary>
            ```bash
            $(cat i18n_update.log)
            ```
            </details>

